apiVersion: obs.bpfprograms.io/v1alpha1
kind: BpfProgram
metadata:
  labels:
    app.kubernetes.io/name: gpu-bpf-operator
    app.kubernetes.io/managed-by: kustomize
  name: bpfprogram-sample
spec:
  # TODO(user): Add fields here
